apiVersion: v1
kind: Pod
metadata:
  name: webapp
  app: employees
  spec:
    containers:
   - name: webapp
     image: 718227961166.dkr.ecr.us-east-1.amazonaws.com/web-repo:v1.0
     env:
     - name: DBUSER
        value: "root"
      - name: DATABASE
      value: "employees"
    - name: DBPWD
      value: "pw"
    - name: APP_COLOR
      value: "pink"
    - name: DBPORT
      value: "3306"
    - name: DBHOST
      value: mysql
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
    - containerPort: 8080
  imagePullSecrets:
    - name: regcred