apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: sqldb
        image: 718227961166.dkr.ecr.us-east-1.amazonaws.com/mysql-repo:v1.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"
        ports:
        - containerPort: 3306
      imagePullSecrets:
      - name: regcred