apiVersion: v1
kind: Pod
metadata:
  name: mysql
  app: mysql
spec:
  containers:
  - name: mysql
    image: 718227961166.dkr.ecr.us-east-1.amazonaws.com/mysql-repo:v1.0
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"
    ports:
    - containerPort: 3306
  imagePullSecrets:
  - name: regcred