apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: employees
spec:
  selector:
    matchLabels:
      app: employees
  replicas: 3    
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - image: 380295710645.dkr.ecr.us-east-1.amazonaws.com/webapp:v1.22
        name: webapp
        env:
        - name: DBHOST
          value: 10.244.0.7
        - name: DBPORT
          value: "3306"  
        - name: DBUSER
          value: root
        - name: DATABASE
          value: employees
        - name: DBPWD
          value: pw
        - name: APP_COLOR
          value: pink  
        ports:
        - containerPort: 8080